package forge.neo.match;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;

import forge.deck.Deck;
import forge.game.GameType;
import forge.game.player.RegisteredPlayer;
import forge.gamemodes.quest.QuestController;
import forge.item.PreconDeck;
import forge.model.FModel;
import forge.util.storage.IStorage;

/**
 * Los formatos de partida que ofrece el menu.
 *
 * <p>Forge ya trae TODOS los modos programados: lo unico que cambia entre
 * jugar Commander y jugar Estandar es el {@link GameType} que se le pasa a
 * {@code HostedMatch} y de que carpeta salen los mazos. Este enum es esa tabla,
 * y nada mas — aqui no hay ni una regla de juego.
 *
 * <p>Los modos que NO estan aqui (Quest, Draft, Sellado, Conquista) no faltan
 * por el motor, que los tiene: les falta pantalla propia. Un draft necesita una
 * interfaz de picks y Quest una campana entera con tienda y progresion. Ver
 * el plan del proyecto.
 */
public enum NeoFormat implements forge.neo.deck.DeckContext {

    COMMANDER("Commander", GameType.Commander,
            "100 cartas, un comandante, 40 vidas", 3),

    ESTANDAR("Estandar", GameType.Constructed,
            "Construido normal, 60 cartas y 20 vidas", 1),

    BRAWL("Brawl", GameType.Brawl,
            "Commander en formato Estandar, 25 vidas", 1),

    OATHBREAKER("Oathbreaker", GameType.Oathbreaker,
            "Un planeswalker de comandante y su hechizo", 3),

    TINY_LEADERS("Tiny Leaders", GameType.TinyLeaders,
            "Commander de 50 cartas con coste 3 o menos", 1),

    /**
     * Limitado: el mazo sale de un draft, no de tu coleccion.
     *
     * <p>No sale como una casilla mas del menu porque no se entra a el
     * eligiendo mazo: se entra drafteando. Ver {@code forge.neo.draft}.
     */
    DRAFT("Draft", GameType.Draft,
            "40 cartas montadas con lo que hayas draftado", 1),

    /**
     * Limitado tambien, pero sin pasar sobres: te dan seis y montas.
     *
     * <p>Es un {@code GameType} distinto del draft y hay que respetarlo — el
     * motor lo usa para los logros y para las estadisticas — aunque las reglas
     * de mesa sean las mismas: veinte vidas y el mazo tal cual.
     */
    SELLADO("Sellado", GameType.Sealed,
            "40 cartas montadas con seis sobres", 1),

    // -----------------------------------------------------------------
    // "Otros formatos": el mismo Construido de siempre (o el mismo
    // Commander, en PreDH), con un pozo de cartas mas estrecho encima.
    // No salen en el menu principal (isInMainMenu()) — se entra por la
    // pantalla nueva de la auditoría del motor — y comparten carpeta
    // de mazos con ESTANDAR o COMMANDER: un mazo legal aqui lo es tambien
    // alli, porque el pozo solo puede RECORTAR, nunca ampliar.
    // -----------------------------------------------------------------

    STANDARD("Standard", GameType.Constructed,
            "El Standard de verdad: solo las ediciones mas recientes", 1, "Standard"),

    PIONEER("Pioneer", GameType.Constructed,
            "Construido desde el bloque Kaladesh en adelante", 1, "Pioneer"),

    HISTORIC("Historic", GameType.Constructed,
            "El pool digital de Arena, con sus cartas propias", 1, "Historic"),

    MODERN("Modern", GameType.Constructed,
            "Construido desde la Octava Edicion en adelante", 1, "Modern"),

    LEGACY("Legacy", GameType.Constructed,
            "Construido con casi toda la historia de Magic, sin restricciones", 1, "Legacy"),

    VINTAGE("Vintage", GameType.Constructed,
            "Toda la historia de Magic. Nada prohibido, algunas cartas restringidas a una copia",
            1, "Vintage"),

    EXTENDED("Extended", GameType.Constructed,
            "A medio camino entre Standard y Modern", 1, "Extended"),

    PAUPER("Pauper", GameType.Constructed,
            "Solo cartas comunes", 1, "Pauper"),

    PREMODERN("Premodern", GameType.Constructed,
            "Construido con las ediciones de 1999 a 2003", 1, "Premodern"),

    /**
     * El unico "otro formato" que es Commander de verdad: 100 cartas, zona de
     * mando e identidad de color, pero solo con ediciones anteriores a 2020.
     */
    PREDH("PreDH", GameType.Commander,
            "Commander con las ediciones anteriores a Commander Legends (2020)", 3, "PreDH"),

    /**
     * El mazo se monta SOLO: 60 tierras basicas y un avatar. No hay deck
     * builder ni mazo que elegir para ninguno de los dos — ver
     * {@code isAutoGenerated()} y {@link #register}.
     */
    MOMIR("Momir Basic", GameType.MomirBasic,
            "Tierras basicas y nada mas. Lanzas criaturas al azar con la habilidad de Momir Vig",
            1),

    MOJHOSTO("MoJhoSto", GameType.MoJhoSto,
            "Como Momir Basic, pero con tres avatares y tres habilidades a la vez", 1);

    private final String label;
    private final GameType gameType;
    private final String description;
    private final int defaultOpponents;

    /**
     * El nombre del {@code GameFormat} de {@code res/formats/} que recorta el
     * pozo de cartas, o null si este formato no tiene ninguno mas alla de sus
     * reglas de construccion (los siete de siempre).
     */
    private final String poolFormatName;

    NeoFormat(final String label, final GameType gameType, final String description,
              final int defaultOpponents) {
        this(label, gameType, description, defaultOpponents, null);
    }

    NeoFormat(final String label, final GameType gameType, final String description,
              final int defaultOpponents, final String poolFormatName) {
        this.label = label;
        this.gameType = gameType;
        this.description = description;
        this.defaultOpponents = defaultOpponents;
        this.poolFormatName = poolFormatName;
    }

    /**
     * Como se llama el formato en pantalla.
     *
     * <p>Casi todos son nombres propios que no se traducen ("Commander",
     * "Brawl"), pero "Estandar" si, asi que pasan todos por la tabla y quien
     * no tenga entrada se queda con el nombre de aqui.
     */
    @Override
    public String getLabel() {
        final String key = "format." + name() + ".label";
        final String translated = forge.neo.NeoText.get(key);
        return key.equals(translated) ? label : translated;
    }

    public GameType getGameType() {
        return gameType;
    }

    /**
     * Las reglas de construccion de este formato. Las pone el motor.
     *
     * <p>Es lo unico que el deck builder necesita saber de un formato, y por
     * eso {@code NeoFormat} vale directamente como {@code DeckContext}: el
     * catalogo es todo Magic y el cajon es la carpeta del formato, que son los
     * valores por defecto.
     */
    @Override
    public forge.deck.DeckFormat deckFormat() {
        return gameType.getDeckFormat();
    }

    /** La linea que explica el formato a quien no lo conoce. */
    public String getDescription() {
        final String key = "format." + name() + ".desc";
        final String translated = forge.neo.NeoText.get(key);
        return key.equals(translated) ? description : translated;
    }

    /** Cuantos rivales tiene sentido por defecto en este formato. */
    public int getDefaultOpponents() {
        return defaultOpponents;
    }

    /**
     * El pozo de cartas adicional de este formato (sets legales, prohibidas,
     * restringidas), o null si solo mandan las reglas de construccion.
     *
     * <p>Se resuelve TARDE y no en el constructor: el enum se inicializa antes
     * de que {@code FModel} tenga las 44 tablas de {@code res/formats/}
     * cargadas, y ademas es {@code FModel.getFormats()} quien decide —
     * segun {@code FPref.LOAD_ARCHIVED_FORMATS} — que formatos existen.
     */
    @Override
    public forge.game.GameFormat poolFormat() {
        return poolFormatName == null ? null : FModel.getFormats().getFormat(poolFormatName);
    }

    /**
     * Si el formato juega con comandante (y por tanto con zona de mando).
     *
     * <p>Lo decide el {@code DeckFormat}, no una lista de exclusiones: es la
     * misma pregunta que ya se hace {@code DeckEditor.usesCommander()}, y asi
     * un formato nuevo no puede olvidarse de añadirse a la lista.
     */
    public boolean isCommanderStyle() {
        return deckFormat().hasCommander();
    }

    /**
     * Si aparece como una casilla del menu principal.
     *
     * <p>Al draft no se entra eligiendo mazo, se entra drafteando: tiene su
     * propia casilla y su propia pantalla. Y los formatos con pozo propio
     * (Modern, Pioneer, Pauper...) no son un modo nuevo — son el Construido o
     * el Commander de siempre con menos cartas — asi que no se meten como
     * casilla suelta: se entra por "Otros formatos" (seccion 2 de
     * la auditoría del motor), que lleva a la MISMA pantalla de mazos.
     */
    public boolean isInMainMenu() {
        return poolFormatName == null && this != DRAFT && this != SELLADO
                && this != MOMIR && this != MOJHOSTO;
    }

    /**
     * Si el mazo se monta SOLO (Momir Basic, MoJhoSto): sin deck builder,
     * sin pantalla de mazos, directos a la partida.
     */
    public boolean isAutoGenerated() {
        return gameType.isAutoGenerated();
    }

    /**
     * Los mazos que se pueden jugar en este formato.
     *
     * <p>Cada formato tiene SU carpeta en {@code %APPDATA%\\Forge\\decks\\}. En
     * Estandar se anyaden ademas los mazos preconstruidos que trae Forge: sin
     * ellos, quien no se haya montado un mazo de 60 cartas se encuentra una
     * lista vacia y el modo no sirve de nada.
     */
    public List<Deck> decks() {
        final List<Deck> out = new ArrayList<>();
        switch (this) {
            case COMMANDER:
            // PreDH es Commander con un pozo mas viejo (seccion 2 de
            // la auditoría del motor): mismos mazos de partida, el pozo ya se aplica
            // aparte en poolFormat().
            case PREDH:
                FModel.getDecks().getCommander().forEach(out::add);
                // Los preconstruidos de Commander que trae Forge. Son mazos
                // enteros y equilibrados, asi que valen tanto para jugar tu
                // como — sobre todo — para dárselos a los rivales y que cada
                // uno lleve algo distinto.
                FModel.getDecks().getCommanderPrecons().forEach(out::add);
                break;
            case MOMIR:
            case MOJHOSTO:
                // El mazo se monta solo (GameType.autoGenerateDeck) y no se
                // guarda en ningun sitio: no hay ninguno que listar.
                break;
            case BRAWL:
                FModel.getDecks().getBrawl().forEach(out::add);
                break;
            case OATHBREAKER:
                FModel.getDecks().getOathbreaker().forEach(out::add);
                break;
            case TINY_LEADERS:
                FModel.getDecks().getTinyLeaders().forEach(out::add);
                break;
            case DRAFT:
                // El "mazo" de un draft es el que salio de sus 45 cartas.
                for (final forge.deck.DeckGroup g : FModel.getDecks().getDraft()) {
                    if (g.getHumanDeck() != null) {
                        out.add(g.getHumanDeck());
                    }
                }
                break;
            case SELLADO:
                for (final forge.deck.DeckGroup g : FModel.getDecks().getSealed()) {
                    if (g.getHumanDeck() != null) {
                        out.add(g.getHumanDeck());
                    }
                }
                break;
            case ESTANDAR:
            default:
                FModel.getDecks().getConstructed().forEach(out::add);
                addPrecons(out);
                break;
        }
        return out;
    }

    /**
     * Donde se guardan los mazos de este formato.
     *
     * <p>Es la MISMA carpeta que usa la instalacion normal de Forge, asi que un
     * mazo montado aqui se puede jugar tambien desde la GUI vieja, y al reves.
     * El {@code IStorage} escribe el {@code .dck} y deja el mazo disponible en
     * la pantalla de inicio sin reiniciar.
     *
     * <p>Estandar guarda en la carpeta de construido: los preconstruidos que
     * trae Forge se leen pero no se sobrescriben nunca.
     */
    @Override
    public IStorage<Deck> storage() {
        switch (this) {
            case COMMANDER:
            case PREDH:
                return FModel.getDecks().getCommander();
            case BRAWL:
                return FModel.getDecks().getBrawl();
            case OATHBREAKER:
                return FModel.getDecks().getOathbreaker();
            case TINY_LEADERS:
                return FModel.getDecks().getTinyLeaders();
            case ESTANDAR:
            default:
                return FModel.getDecks().getConstructed();
        }
    }

    /**
     * Si este mazo es tuyo (esta en tu carpeta) o viene con Forge.
     *
     * <p>Sirve para marcarlos en la pantalla: con los preconstruidos dentro, la
     * lista se llena y conviene distinguir de un vistazo cuales has montado tu.
     */
    public boolean isMine(final Deck deck) {
        if (deck == null) {
            return false;
        }
        if (this == DRAFT || this == SELLADO) {
            // Aqui el mazo no vive suelto: es la mitad humana de un evento
            // entero (DeckGroup), y storage() apunta a otra carpeta.
            return groupOf(deck) != null;
        }
        return storage().contains(deck.getName());
    }

    /**
     * Si este mazo se puede borrar.
     *
     * <p>Solo los tuyos. Los preconstruidos de Forge no son tuyos y ademas
     * volverian a salir al arrancar (se leen de {@code res/}), asi que una
     * papelera ahi seria un boton que no hace nada. Y los bajados de internet
     * son una <b>descarga por categorias</b>: borrar uno suelto no significa
     * nada, se rehace con la siguiente descarga.
     */
    public boolean canDelete(final Deck deck) {
        return isMine(deck);
    }

    /**
     * Borra un mazo tuyo. Devuelve true si de verdad se ha ido.
     *
     * <p>Escribe en la MISMA carpeta que la instalacion normal de Forge, asi
     * que esto borra el {@code .dck} de verdad y para siempre: quien lo llame
     * tiene que haber preguntado antes.
     *
     * <p>Draft y sellado son el caso raro: lo que se borra no es un mazo, es el
     * <b>evento entero</b> — tu mazo y los de los siete rivales viven en el
     * mismo {@code DeckGroup} y no se pueden separar.
     */
    public boolean delete(final Deck deck) {
        if (!canDelete(deck)) {
            return false;
        }
        if (this == DRAFT) {
            return deleteGroup(FModel.getDecks().getDraft(), deck);
        }
        if (this == SELLADO) {
            return deleteGroup(FModel.getDecks().getSealed(), deck);
        }
        storage().delete(deck.getName());
        return !storage().contains(deck.getName());
    }

    /** El evento (draft o sellado) del que salio este mazo, o null. */
    private forge.deck.DeckGroup groupOf(final Deck deck) {
        final IStorage<forge.deck.DeckGroup> groups = this == DRAFT
                ? FModel.getDecks().getDraft()
                : this == SELLADO ? FModel.getDecks().getSealed() : null;
        if (groups == null) {
            return null;
        }
        for (final forge.deck.DeckGroup g : groups) {
            final Deck human = g.getHumanDeck();
            // Por objeto Y por nombre: decks() devuelve el mazo del grupo tal
            // cual, asi que casi siempre es el mismo objeto — pero volver a
            // leer del disco daria otro, y entonces la papelera no borraria
            // nada sin decir por que.
            if (human == deck || (human != null && human.getName().equals(deck.getName()))) {
                return g;
            }
        }
        return null;
    }

    private boolean deleteGroup(final IStorage<forge.deck.DeckGroup> groups, final Deck deck) {
        final forge.deck.DeckGroup group = groupOf(deck);
        if (group == null) {
            return false;
        }
        groups.delete(group.getName());
        return !groups.contains(group.getName());
    }

    /**
     * Los preconstruidos que Forge trae de serie (unos 500), <b>menos los de
     * Commander</b>.
     *
     * <p>En {@code res/quest/precons} no hay solo mazos de construido: hay 64
     * preconstruidos de Commander mezclados. En Estandar el asiento se registra
     * con {@code new RegisteredPlayer(deck)}, que <b>ignora la seccion de
     * mando</b>, asi que uno de esos entraba a la partida como una biblioteca
     * de 99 cartas y la zona de mando vacia: el mazo sin su comandante, que es
     * justo lo que no se puede jugar.
     *
     * <p>No se pierde nada al quitarlos: los 173 preconstruidos de Commander
     * de verdad ({@code res/quest/commanderprecons}) ya salen en la lista de
     * Commander, y estos 64 son copias suyas.
     */
    private static void addPrecons(final List<Deck> out) {
        out.addAll(precons());
    }

    /**
     * Los mismos, sueltos.
     *
     * <p>Los pide Ascenso para los rivales de sus nodos: ahi el pozo NO puede
     * ser {@code decks()}, que mete tambien los mazos del jugador — jugar
     * contra tu propio mazo no es un rival, es un espejo.
     */
    public static List<Deck> precons() {
        final List<Deck> out = new ArrayList<>();
        try {
            for (final PreconDeck precon : QuestController.getPrecons()) {
                final Deck deck = precon.getDeck();
                if (deck != null && !isCommanderDeck(deck)) {
                    out.add(deck);
                }
            }
        } catch (final RuntimeException e) {
            // Sin preconstruidos se puede jugar con los tuyos; no es fatal.
            System.err.println("[neo] no se han podido leer los mazos preconstruidos: " + e);
        }
        return out;
    }

    /**
     * Si este preconstruido es en realidad un mazo de Commander.
     *
     * <p>Casi todos se reconocen por la seccion de mando, que es el dato de
     * verdad. Pero cuatro (los de C18: <i>Adaptive Enchantment</i>,
     * <i>Exquisite Invention</i>, <i>Nature's Vengeance</i> y <i>Subjective
     * Reality</i>) traen el comandante <b>dentro de {@code [Main]}</b> — el
     * {@code +} del fichero no marca comandante, marca foil — y por estructura
     * son indistinguibles de un mazo de construido enorme.
     *
     * <p>A esos se llega por lo que son: cien cartas sin una sola repetida. Un
     * mazo de construido de ese tamanyo lleva copias (el <i>Quick Start Set:
     * Rivals</i>, de 112 cartas, lleva cuatro Montanyas y tres Terror), asi que
     * el singleton es lo que los separa — y por eso la comprobacion mira las
     * copias y no el tamanyo a secas.
     */
    private static boolean isCommanderDeck(final Deck deck) {
        if (deck.has(forge.deck.DeckSection.Commander)) {
            return true;
        }
        final forge.deck.CardPool main = deck.getMain();
        final int size = main.countAll();
        if (size < 99 || size > 100) {
            return false;
        }
        for (final java.util.Map.Entry<forge.item.PaperCard, Integer> e : main) {
            final forge.card.CardRules rules = e.getKey().getRules();
            if (e.getValue() > 1 && (rules == null || !rules.getType().isBasicLand())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Registra un asiento con este mazo.
     *
     * <p>La diferencia entre formatos es de VIDAS y de comandante, y de eso ya
     * sabe {@code RegisteredPlayer}: {@code forVariants} aplica lo que toque
     * segun el {@link GameType}. Reimplementarlo aqui seria inventar reglas.
     */
    public RegisteredPlayer register(final Deck deck, final int playerCount) {
        // Estandar Y los formatos construidos de "Otros formatos" (mismo
        // GameType.Constructed, distinto pozo) son un asiento normal: 20
        // vidas y el mazo tal cual. Limitado tambien.
        if (deckFormat() == forge.deck.DeckFormat.Constructed || this == DRAFT || this == SELLADO) {
            return new RegisteredPlayer(deck);
        }
        if (this == COMMANDER || this == PREDH) {
            return RegisteredPlayer.forCommander(deck);
        }
        return RegisteredPlayer.forVariants(playerCount, EnumSet.of(gameType), deck,
                null, false, null, null);
    }

    @Override
    public String toString() {
        return label;
    }
}
